app = "ode-seoul"
primary_region = "nrt"

[build]
image = "njw1204/ode-seoul:latest"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = false

[env]
TZ = "Asia/Seoul"
