server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: -1

spring:
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:mysql://${ODE_SEOUL_DB_HOSTNAME}:${ODE_SEOUL_DB_PORT}/${ODE_SEOUL_DB_SCHEMA}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${ODE_SEOUL_DB_USERNAME}
    password: ${ODE_SEOUL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    user:
      name: ${ODE_SEOUL_SECURITY_USERNAME}
      password: ${ODE_SEOUL_SECURITY_PASSWORD}
      roles: ADMIN
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    disable-swagger-default-url: false
    operations-sorter: alpha
    tags-sorter: alpha
    persist-authorization: true
  cache:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - env
          - health
          - mappings
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always

decorator:
  datasource:
    p6spy:
      enable-logging: false

ode-seoul:
  security:
    jwt-secret: ${ODE_SEOUL_JWT_SECRET}
    access-token-duration-seconds: ${ODE_SEOUL_ACCESS_TOKEN_DURATION_SECONDS}
  kakao:
    client-id: ${ODE_SEOUL_KAKAO_CLIENT_ID}
  image-kit:
    url-endpoint: ${ODE_SEOUL_IMAGE_KIT_URL_ENDPOINT}
    public-key: ${ODE_SEOUL_IMAGE_KIT_PUBLIC_KEY}
    private-key: ${ODE_SEOUL_IMAGE_KIT_PRIVATE_KEY}
