name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - ode-seoul/**

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: docker/setup-buildx-action@v2
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            njw1204/ode-seoul
          tags: |
            type=raw,value={{branch}}-{{date 'YYYYMMDD' tz='Asia/Seoul'}}
            type=raw,value=latest,enable={{is_default_branch}}
      - uses: docker/login-action@v2
        with:
          username: njw1204
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ode-seoul
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-main
          cache-to: type=gha,mode=max,scope=build-main
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.0.559
      - run: flyctl deploy
        working-directory: ode-seoul
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
